# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Minesweep < Formula
  desc "Policy-driven secrets and sensitive data scanner with git history forensics"
  homepage "https://github.com/Hxmbl/minesweep"
  version "2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hxmbl/minesweep/releases/download/v2/minesweep_2_Darwin_x86_64.tar.gz"
      sha256 "d01b77c5bd0d78e756bc6b8db8fe8e36a5b671c53c19cc67c70891e185c78b23"

      define_method(:install) do
        bin.install "minesweep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hxmbl/minesweep/releases/download/v2/minesweep_2_Darwin_arm64.tar.gz"
      sha256 "9246e0465873df9e7881923b4612d49628bfd2f4dfbcce242753001880108b83"

      define_method(:install) do
        bin.install "minesweep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hxmbl/minesweep/releases/download/v2/minesweep_2_Linux_x86_64.tar.gz"
      sha256 "c97376abc5580ec524ca2cb097e434ce166eb7cbd2d580f57acc44423dddc0f8"
      define_method(:install) do
        bin.install "minesweep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hxmbl/minesweep/releases/download/v2/minesweep_2_Linux_arm64.tar.gz"
      sha256 "c25cc75fd15a11f89678750c53e87a82f75aabf9dcdbae954dcd357a9c01bf94"
      define_method(:install) do
        bin.install "minesweep"
      end
    end
  end

  test do
    system "#{bin}/minesweep", "version"
  end
end
