# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Minesweep < Formula
  desc "Policy-driven secrets and sensitive data scanner with git history forensics."
  homepage "https://github.com/Hxmbl/minesweep"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hxmbl/minesweep/releases/download/v1.0.0/minesweep_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "a8be2f6cda4730a86c52baab60ad9b8abc9623bb41a4d3b7b1f141c811e82ac9"

      define_method(:install) do
        bin.install "minesweep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hxmbl/minesweep/releases/download/v1.0.0/minesweep_1.0.0_Darwin_arm64.tar.gz"
      sha256 "8241f8cd6305fc3ae79af49db5f03e15846f2d0ca4d19864a71c15ce3a22a169"

      define_method(:install) do
        bin.install "minesweep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hxmbl/minesweep/releases/download/v1.0.0/minesweep_1.0.0_Linux_x86_64.tar.gz"
      sha256 "c1c2c109af024d0417f7700c12602226fbb43c01eacde9952d0f44631019cd0c"
      define_method(:install) do
        bin.install "minesweep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hxmbl/minesweep/releases/download/v1.0.0/minesweep_1.0.0_Linux_arm64.tar.gz"
      sha256 "d6529c7616f073ceed359f83cfd79f483f018289a2496aeb5786be2a2bef16cf"
      define_method(:install) do
        bin.install "minesweep"
      end
    end
  end

  test do
    system "#{bin}/minesweep version"
  end
end
