# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Minesweep < Formula
  desc "Policy-driven secrets and sensitive data scanner with git history forensics"
  homepage "https://github.com/hxmbl/minesweep"
  version "2.3.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hxmbl/minesweep/releases/download/v2.3.6/minesweep_2.3.6_Darwin_x86_64.tar.gz"
      sha256 "7f528d0484dd2b7ff4ada17267b08c0dfaf02f219cfdfea9c6391e86d14f77dd"

      define_method(:install) do
        bin.install "minesweep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hxmbl/minesweep/releases/download/v2.3.6/minesweep_2.3.6_Darwin_arm64.tar.gz"
      sha256 "7679b18fd1e2b6cc0b95d29a994f9fb32e11480e9169fe7139da5973c9bb9262"

      define_method(:install) do
        bin.install "minesweep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hxmbl/minesweep/releases/download/v2.3.6/minesweep_2.3.6_Linux_x86_64.tar.gz"
      sha256 "b787220d4a2e40799c707b542628126b7fd92df5dc847b6d06689105196a7eb4"
      define_method(:install) do
        bin.install "minesweep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hxmbl/minesweep/releases/download/v2.3.6/minesweep_2.3.6_Linux_arm64.tar.gz"
      sha256 "d34737cb9980078403c4466f007f7fd9ad18adfedfabb04c59b5582e8b6a3230"
      define_method(:install) do
        bin.install "minesweep"
      end
    end
  end

  test do
    system "#{bin}/minesweep", "version"
  end
end
