# typed: false
# frozen_string_literal: true

# This file was generated by the release workflow. DO NOT EDIT.
class Purgable < Formula
  desc "Recursively find files named exactly PURGABLE and ask before deleting them."
  homepage "https://github.com/Hxmbl/purgable"
  version "1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hxmbl/purgable/releases/download/v1.5/purgable_1.5_Darwin_x86_64.tar.gz"
      sha256 "ac951891c260245834d4b01a66778eab6746bbafb6d7833e93cd316ea05ef22b"

      define_method(:install) do
        bin.install "purgable"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hxmbl/purgable/releases/download/v1.5/purgable_1.5_Darwin_arm64.tar.gz"
      sha256 "1a4397eac2ce1c1a7caec673a15b9d7121435dd6b213822f2a0c7ec54ada35ec"

      define_method(:install) do
        bin.install "purgable"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hxmbl/purgable/releases/download/v1.5/purgable_1.5_Linux_x86_64.tar.gz"
      sha256 "dcf6fc99b220102814e88fb44b3522097be9906aab3b4a012037d17a364b01ca"

      define_method(:install) do
        bin.install "purgable"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hxmbl/purgable/releases/download/v1.5/purgable_1.5_Linux_arm64.tar.gz"
      sha256 "7df84af8eea65a830769918f7c42a3f8abca072d52cbb9e005a07ca1c45dd540"

      define_method(:install) do
        bin.install "purgable"
      end
    end
  end

  test do
    system "#{bin}/purgable --help"
  end
end
